name: omnisphere_vault
description: A secure, cross-platform password manager
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^16.3.2
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite: ^2.4.0
  animations: ^2.0.11
  sqflite_sqlcipher: ^3.1.0+1
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  encrypt: ^5.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
